alter table ACCOUNT drop foreign key FK9rxadd7hdlmarov6qbvaot0po;
alter table ACCOUNT drop foreign key FK4cfkq2sywnlcu6fxm9xbrmsjs;
alter table SUPPLIER drop foreign key FKiiacflcflh0lvcr8nbevvg0h3;
alter table SUPPLIER drop foreign key FKf1ovwe1gt81p4du64yfmbfo1h;
alter table SUPPLY drop foreign key FKcvv6w5ejrml8v85sgqqsv1r3g;
alter table SUPPLY drop foreign key FK206oa0h867i5f62tu92qwxcbl;
alter table SUPPLY drop foreign key FK6qv2xhybk3g4dp68y4edu54n;
drop table if exists ACCOUNT;
drop table if exists SUPPLIER;
drop table if exists SUPPLY;
create table ACCOUNT (id integer not null auto_increment, FIRST_CREATED datetime not null, LAST_MODIFIED datetime, CREATED_BY integer, MODIFIED_BY integer, primary key (id));
create table SUPPLIER (id integer not null auto_increment, FIRST_CREATED datetime not null, LAST_MODIFIED datetime, NAME varchar(32) not null, CREATED_BY integer, MODIFIED_BY integer, primary key (id));
create table SUPPLY (id integer not null auto_increment, FIRST_CREATED datetime not null, LAST_MODIFIED datetime, CAR_NUMBER varchar(10) not null, DEPARTMENT varchar(255), DOCUMENT_RECEIVING varchar(255), DRIVER_NAME varchar(255) not null, PHONE varchar(255) not null, PRODUCT varchar(255), STOREKEEPER varchar(255), CREATED_BY integer, MODIFIED_BY integer, SUPPLIER_ID integer, primary key (id));
alter table ACCOUNT add constraint FK9rxadd7hdlmarov6qbvaot0po foreign key (CREATED_BY) references ACCOUNT (id);
alter table ACCOUNT add constraint FK4cfkq2sywnlcu6fxm9xbrmsjs foreign key (MODIFIED_BY) references ACCOUNT (id);
alter table SUPPLIER add constraint FKiiacflcflh0lvcr8nbevvg0h3 foreign key (CREATED_BY) references ACCOUNT (id);
alter table SUPPLIER add constraint FKf1ovwe1gt81p4du64yfmbfo1h foreign key (MODIFIED_BY) references ACCOUNT (id);
alter table SUPPLY add constraint FKcvv6w5ejrml8v85sgqqsv1r3g foreign key (CREATED_BY) references ACCOUNT (id);
alter table SUPPLY add constraint FK206oa0h867i5f62tu92qwxcbl foreign key (MODIFIED_BY) references ACCOUNT (id);
alter table SUPPLY add constraint FK6qv2xhybk3g4dp68y4edu54n foreign key (SUPPLIER_ID) references SUPPLIER (id);
insert into supplier (id, FIRST_CREATED, name) VALUES(1, now(), "test");
insert into supply(id, FIRST_CREATED, CAR_NUMBER,DRIVER_NAME,PHONE) VALUES(1,now(),"AA26-30CF","Пяточкин Петя","097-112-54-87");